security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        main:
            lazy: true
            provider: app_user_provider

            custom_authenticator: App\Security\SecurityControllerAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout

            # Préciser clairement l'entry_point :
            entry_point: form_login
                # by default, the feature is enabled by checking a checkbox in the
                # login form, uncomment the following line to always enable it.
                #always_remember_me: true
            # Uncomment if you implement remember me:
            # remember_me:
            #     secret: '%kernel.secret%'
            #     lifetime: 604800 # 1 semaine

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/event, roles: ROLE_ADMIN }
        - { path: ^/registration, roles: ROLE_USER }
